//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZCJT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysFileUpload
    {
        public string Id { get; set; }
        public string FileName { get; set; }
        public string FileExtend { get; set; }
        public string AttachmentGUID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Editor { get; set; }
        public string OwnerID { get; set; }
    }
}
